[package]
name = "disqus-to-hypothesis"
version = "0.1.0"
authors = ["Jichao Ouyang <oyanglulu@gmail.com>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde-xml-rs = "0.2.1"
serde_json = "1.0"
reqwest = "0.9.4"
[[bin]]
name = "disqus-to-hypothesis"
path = "main.rs"
